void monitoring() {
  Serial.print("Oranye: ");
  Serial.print(m / 20);
  Serial.print("   ");
  Serial.print("Cyan: ");
  Serial.print(m1 / 20);
  Serial.print("   ");
  Serial.print("Magenta: ");
  Serial.print(m2 / 20);
  Serial.print("   ");
  Serial.print("Gawang: ");
  Serial.print(m3 / 20);
  Serial.print("   ");
  Serial.print("Kostum: ");
  Serial.print(m5);
  Serial.print("   ");
  Serial.print("Ball: ");
  Serial.print(valballdtc);
  Serial.print("   ");
  Serial.print("line 1: ");
  Serial.print(valline1);
  Serial.print("   ");
  Serial.print("line 2: ");
  Serial.print(valline2);
  Serial.print("   ");
  Serial.print("Remote: ");
  Serial.print(rimut);
  Serial.print("   ");
  Serial.print("kondisi: ");
  Serial.print(kondisi);
  Serial.println("   ");
}
